apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "example.selectorLabels" . | nindent 4 }}
