apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "example.selectorLabels" . | nindent 8 }}
    spec:
      replicas: 1
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: client
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.client_image }}"
          imagePullPolicy: Always
          command: ["python3"]
          env:
            - name: SCONE_CONFIG_ID
              value: {{ .Values.scone.client_session }}
            - name: SCONE_CAS_ADDR
              value: {{ .Values.scone.cas }}
            - name: SCONE_LAS_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SCONE_LOG
              value: "ERROR"
            - name: SCONE_VERSION
              value: "1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
