{{- if not .Values.useSGXDevPlugin }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- else if and (ne .Values.useSGXDevPlugin "enabled") (ne .Values.useSGXDevPlugin "scone") (ne .Values.useSGXDevPlugin "azure") (ne .Values.useSGXDevPlugin "disabled") }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- end }}

{{- if and (eq .Values.useSGXDevPlugin "azure") (not .Values.sgxEpcMem) }}
{{- required "Specify '.Values.sgxEpcMem' when using Azure SGX Device Plugin" .value }}
{{- end }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "example.fullname" . }}-redis-master
  labels:
    app: {{ include "example.fullname" . }}-redis
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
     {{- toYaml . | nindent 8 }}
  {{- end }}
  volumes:
    - name: tls
      emptyDir: {}
    {{- if eq .Values.useSGXDevPlugin "disabled" }}
    - name: dev-isgx
      hostPath:
        path: {{ .Values.sgxDevicePath }}
    {{- end }}
  containers:
    - name: master
      securityContext:
      {{- if .Values.securityContext }}
        {{- toYaml .Values.securityContext | nindent 10 }}
      {{- end }}
      {{- if or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled") }}
        capabilities:
          add: ["SYS_RAWIO"]
      {{- else if eq .Values.useSGXDevPlugin "disabled" }}
        privileged: true
      {{- end }}
      image: {{ .Values.redis.image }}
      imagePullPolicy: Always
      env:
        - name: MASTER
          value: "true"
        - name: SCONE_CONFIG_ID
          value: {{ .Values.scone.redis_session }}
        - name: SCONE_CAS_ADDR
          value: {{ .Values.scone.cas }}
        - name: SCONE_LAS_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
      volumeMounts:
        - name: tls
          mountPath: /tls
      {{- if eq .Values.useSGXDevPlugin "disabled" }}
        - name: dev-isgx
          mountPath: {{ .Values.sgxDevicePath }}
      {{- end }}
      {{- if or (or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled")) (eq .Values.useSGXDevPlugin "azure") }}
      resources:
      {{- if or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled") }}
        limits:
          sgx.k8s.io/sgx: 1
      {{- else if eq .Values.useSGXDevPlugin "azure" }}
        limits:
          kubernetes.azure.com/sgx_epc_mem_in_MiB: {{ .Values.sgxEpcMem }}
      {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    app: {{ include "example.fullname" . }}-redis
