apiVersion: v1
kind: Pod
metadata:
  name: {{ include "example.fullname" . }}-redis-master
  labels:
    app: {{ include "example.fullname" . }}-redis
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
     {{- toYaml . | nindent 8 }}
  {{- end }}
  containers:
    - name: master
      image: {{ .Values.redis.image }}
      imagePullPolicy: Always
      command: ["redis-server"]
      args: ["--port 6379", "--protected-mode no"]
      env:
        - name: MASTER
          value: "true"
        - name: SCONE_VERSION
          value: "1"
        # - name: SCONE_CONFIG_ID
        #   value: {{ .Values.scone.redis_session }}
        # - name: SCONE_CAS_ADDR
        #   value: {{ .Values.scone.cas }}
        # - name: SCONE_LAS_ADDR
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    app: {{ include "example.fullname" . }}-redis
