version: '3.2'
services:
    redis:
        image: redis:6-alpine
        command: redis-server
        ports:
         - "6379"
    python:
        image: native_flask_restapi_image
        depends_on:
         - redis
        ports:
         - "4996:4996"
        links:
         - redis
