# Default values for this chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# configure redis
redis:
  image: registry.scontain.com:5050/clenimar/network-shield-demo/redis:6-alpine-scone5.6.0-9c79a943
  service:
    port: 6379

replicaCount: 1

image: registry.scontain.com:5050/clenimar/network-shield-demo/flask-restapi:0.1
client_image: registry.scontain.com:5050/clenimar/network-shield-demo/client:0.1

# on which port the API is listening
port: 4996

imagePullSecrets:
  - name: sconeapps

scone:
  api_session: "network-shield-demo-server/flask_restapi"
  redis_session: "network-shield-demo-redis/redis"
  client_session: "network-shield-demo-client/client"
  cas: "5-5-0.scone-cas.cf"

# Choose how to access SGX hardware through a Device Plugin.
# Options:
#   scone: Use SCONE SGX device plugin
#   azure: Use Azure's SGX device plugin
#   disabled: Don't use any plugin. Run privileged containers that can read
#     the host's /dev.
useSGXDevPlugin: "scone"

# If useSGXDevPlugin is set to "azure", specify how much
# EPM (in MiB) is required by the pod.
sgxEpcMem: 8

# If useSGXDevPlugin is set to "disabled", specify the path
# for the SGX device in the host: /dev/isgx, /dev/sgx/enclave
# or /dev/sgx_enclave.
sgxDevicePath: /dev/isgx

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4996

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

